version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    networks:
      - db
    depends_on:
      - database

volumes:
  db_data:

networks:
  db:
