swagger: "2.0"
basePath: "/api"
info:
  version: "1.0.0"
  title: "T-POO-700"
  description: "T-POO-700 API"

# TAGS
tags:
- name: "USER"
  description: "CRUD operations for users"
- name: "WORKING TIME"
  description: "CRUD operations for working times"
- name: "CLOCK"
  description: "CRUD operations for clocks"

paths:

# PATHS POUR LES USERS 

  /users:
    post:
      tags:
      - "USER"
      summary: "Post a user"
      parameters:
        - name: "user"
          in: "body"
          description: "Datas for post a user"
          required: false
          schema:
           $ref: "#/definitions/usersData"
      responses:
        200: 
          description: "Successful operation"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/usersResponse"
    get:
      tags:
      - "USER"
      summary: "Get user by email & username"
      parameters:
        - name: "email"
          in: "query"
          description: "The email of the user"
          required: true
          type: "string"
        - name: "username"
          in: "query"
          description: "The username of the user"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/usersResponse"
        404: 
          description: "User not found"
  /users/{id}:
    get:
      tags:
      - "USER"
      summary: "Get user by id"
      parameters:
        - name: "id"
          in: "path"
          description: "The id of the user"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/usersResponse"
        404: 
          description: "User not found"
    delete:
      tags:
      - "USER"
      summary: "Delete user by id"
      parameters:
        - name: "id"
          in: "path"
          description: "The id of the user (broken because contraint key on clock)"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/usersDeleteResponse"
        404: 
          description: "User not found"
    put:
      tags:
      - "USER"
      summary: "Update user by id"
      parameters:
        - name: "id"
          in: "path"
          description: "The id of the user"
          required: true
          type: "integer"
        - name: "user"
          in: "body"
          description: "The new username or email of the user"
          required: false
          schema:
           $ref: "#/definitions/usersData"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/usersResponse"
        404: 
          description: "User not found"

  # PATH POUR LES WORKING TIMES
  /workingtime/{userId}/{id}:
    get:
      tags: 
        - "WORKING TIME"
      summary: "Get a working time of a user based on the id"
      parameters:
        - name : "userId"
          in: path
          description: The is of the user
          required: true
          type: "integer"
        - name : "id"
          in: path
          description: The id of the working time
          required: true
          type: "integer"
      responses: 
        200:
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/workingtimeResponse"
        404:
          description: "User not found"


  /workingtime/{userId}?start=XXX&end=XXX:
    get:
      tags:
      - "WORKING TIME"
      summary: "Get working time of a user based on the start and end time"
      parameters:
        - name: "start"
          in: "query"
          description: "The start of the working time"
          required: true
          type: "string"
        - name: "end"
          in: "query"
          description: "The end of the working time"
          required: true
          type: "string"
      responses:
        200: 
          description: "Successful operation"
          schema:
            $ref: "#/definitions/workingtimeResponse"
  
  /workingtime/{userId}:
    post: 
      tags: 
      - "WORKING TIME"
      summary: "Post a new working time for a user with the userId"
      parameters:
       - name: "working time"
         in: body
         description: "The start of the working time"
         required: true
         schema:
           $ref: "#/definitions/workingtimeData"
      responses:
       200:
         description: "Successful operation"
         schema:
           $ref: "#/definitions/workingtimeResponse"
  
  /workingtime/{id}:
    put:
      tags:
      - "WORKING TIME"
      summary: "Put a working time with the id"
      parameters:
       - name: "working time"
         in: body
         required: true
         schema:
          $ref: "#/definitions/workingtime_no_user"
      responses:
        200:
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/workingtimeResponse"
    
    delete:
      tags:
      - "WORKING TIME"
      summary: "Delete a working time with the id"
      parameters:
       - name: "id"
         in: query
         type: integer
         required: true
      responses:
        200:
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/workingtimeResponse"

  /clocks/{userId}:
    get:
      tags:
      - "CLOCK"
      summary: "Get a clock by user id"
      parameters:
      - name: "userId"
        in: query
        type: integer
        required: true
      responses:
        200:
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/clocksResponse"

    post:
      tags:
      - "CLOCK"
      summary: "Post a clock for a userId"
      parameters:
        - name: "userId"
          in: query
          type: integer
          required: true
        - name: clock
          in: body
          required: true
          schema:
            $ref: "#/definitions/clocksData"


definitions:

  usersData:
    type: "object"  
    properties:
      username:
        type: "string"
      email:
        type: "string"
      password: 
        type: "string"
      team_id:
        type: "integer"
        default: 1
      role_id:
        type: "integer"
        default: 1

  usersDeleteResponse:
    type: "object"  
    properties:
      id:
        type: "integer"
        default: 1

  usersResponse:
    type: "object"  
    properties:
      id:
        type: "integer"
        default: 1
      username:
        type: "string"
      email:
        type: "string"
      team:
        type: "integer"
        default: 1
      role:
        type: "integer"
        default: 1

  workingtimeData:
    type: "object"
    properties:
      start: 
        type: "string"
      end: 
        type: "string"

  workingtimeResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        default: 1
      start: 
        type: "string"
      end: 
        type: "string"
      user_id:
        type: "integer"
        default: 1

  workingtime_no_user:
    type: "object"
    properties:
      start: 
        type: "string"
      end: 
        type: "string"

  clocksResponse:
    type: "object"
    properties:
      id: 
        type: "integer"
        default: 1
      time:
        type: "string"
      status:
        type : "boolean"
        default: true
      "user":
        type: "integer"
        default: 1

  clocksData:
    type: "object"
    properties:
      time:
        type: "string"
      status:
        type : "boolean"
        default: true
    
