name: CI Front


on:
    push:
        branches:
            - feat/poo15/ci-vitest

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm install

            - name: Change directory
              run: cd frontend

            - name: Run tests
              run: npm run test:unit
